export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const CLEAR_RESTAURANTS = 'CLEAR_RESTAURANTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';